name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NUGET_URL: https://nuget.pkg.github.com/joelvaneenwyk/index.json
  PROJECT_NAME: OfflinePasswordCheck
  PROJECT_VERSION: 1.7.11.0

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, Any CPU]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/joelvaneenwyk/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore Packages
      run: nuget restore

    - name: Build
      run: msbuild "${{ env.PROJECT_NAME }}.sln" /p:Configuration="${{ matrix.configuration }}" /p:Platform="${{ matrix.platform }}"

    - name: Create Package
      run: |
        dotnet pack "${{ env.PROJECT_NAME }}" \
        -c Release \
        -o ./out \
        -p:PackageVersion=${{ env.PROJECT_VERSION }}

    - name: Publish to GitHub Packages
      if: endsWith(github.ref, '/main')
      run: |
        dotnet nuget push \
        ./out/${{ env.PROJECT_NAME }}.${{ env.PROJECT_VERSION }}.nupkg \
        --source ${{ env.NUGET_URL }} \
        --api-key ${{ secrets.GITHUB_TOKEN }}
