name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, Any CPU]

    runs-on: windows-latest
    env:
      Solution_Name: HIBPOfflineCheck.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/joelvaneenwyk/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore Packages
      run: nuget restore

    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration="${{ matrix.configuration }}" /p:Platform="${{ matrix.platform }}"

    - name: Build solution and generate NuGet package
      run: |
        dotnet pack -c Release -o out

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true
